const jsonData = [
    {
        "@odata.etag": "W/\"JzEwMzI0Njk2MjgsNTYzNzE1MjgzMzswLDA7NzMyMTc1MDQ1LDU2MzcyOTc2NDM7MCwwOzAsMDswLDA7MCwwJw==\"",
        "dataAreaId": "gfs",
        "InventoryLotId": "LOTI-041118",
        "RequestedReceiptDate": "1900-01-01T12:00:00Z",
        "DefaultLineNumberFromLineCreationSequenceNumber": "No",
        "RetailCalculatedTotalDiscountPercentage": 0,
        "EInvoiceDimensionAccountCode": "",
        "FormattedDelveryAddress": "501 ARBORWAY\nJAMAICA PLAIN, MA 02130 \nUSA",
        "ShippingWarehouseLocationId": "",
        "SalesOrderLineStatus": "Invoiced",
        "ProjectCategoryId": "",
        "ExcludeFromMasterPlanning": "No",
        "ItemNumber": "19713",
        "DeliveryAddressDescription": "BICON DENTAL IMPLANTS",
        "MultilineDiscountPercentage": 0,
        "ShippingWarehouseId": "15",
        "GiftCardBuyerName": "",
        "GiftCardNumber": "",
        "CustomsDocumentNumber": "",
        "LineDiscountAmount": 0,
        "ProductStyleId": "",
        "ProductConfigurationId": "",
        "DeliverySalesTaxGroupCode": "",
        "IsIntrastatTriangularDeal": "No",
        "MultilineDiscountAmount": 0,
        "ItemBatchNumber": "",
        "DeliveryAddressCountryRegionId": "USA",
        "DeliveryAddressLatitude": 0,
        "IsPriceLocked": "No",
        "DeliveryAddressCity": "JAMAICA PLAIN",
        "SalesProductCategoryName": "",
        "SalesOrderPromisingMethod": "None",
        "ProjectId": "",
        "DeliveryAddressDistrictName": "",
        "ProjectLinePropertyId": "",
        "SalesRebateProductGroupId": "",
        "DeliveryAddressCountyId": "Suffolk",
        "SalesUnitSymbol": "ea",
        "SalesDeliverNow": 0,
        "ItemWithholdingTaxCodeGroupCode": "",
        "ConfirmedReceiptDate": "2018-03-30T12:00:00Z",
        "ProductSizeId": "",
        "FixedPriceCharges": 0,
        "DeliveryAddressZipCode": "02130",
        "DeliveryAddressDunsNumber": "",
        "DeliveryTermsId": "COL",
        "IsSoftReservedExternally": "No",
        "ServiceFiscalInformationCode": "",
        "RetailCalculatedTotalDiscountAmount": 0,
        "DeliveryAddressName": "BICON DENTAL IMPLANTS",
        "PackingUnitSymbol": "",
        "OrderedSalesQuantity": 9,
        "BOMId": "",
        "CreditNoteReasonCode": "",
        "DeliveryAddressStreetNumber": "",
        "DeliveryAddressStreetInKana": "",
        "ShippingSiteId": "15",
        "NGPCode": 0,
        "RetailCalculatedLineDiscountAmount": 0,
        "IsDeliveryAddressPrivate": "No",
        "LineCreationSequenceNumber": 1,
        "RetailCalculatedTenderDiscountPercentage": 0,
        "InventoryServiceReservationId": "",
        "MainAccountIdDisplayValue": "",
        "OrderedInventoryStatusId": "Available",
        "GiftCardRecipientEmail": "",
        "DeliveryAddressCountryRegionISOCode": "US",
        "ItemSerialNumber": "",
        "RetailCalculatedManualLineDiscountPercentage": 0,
        "CalculateLineAmount": "Yes",
        "RetailCalculatedPeriodicDiscountAmount": 0,
        "IntrastatTransactionCode": "",
        "CurrencyCode": "USD",
        "DeliveryAddressLocationId": "000087670",
        "RouteId": "",
        "SalesTaxItemGroupCode": "",
        "EInvoicePropertyNumber": "",
        "ProductVersionId": "",
        "CommissionSalesRepresentativeGroupId": "",
        "CustomsDocumentName": "",
        "WillAutomaticInventoryReservationConsiderBatchAttributes": "No",
        "IntrastatStatisticsProcedureCode": "",
        "OverrideSalesTax": "No",
        "LineDescription": "",
        "DeliveryAddressStreet": "501 ARBORWAY",
        "DeliveryModeCode": "UPS",
        "ConfirmedShippingDate": "2018-03-30T12:00:00Z",
        "FullRunCTPStatus": "Ready",
        "RetailCalculatedLineDiscountPercentage": 0,
        "SalesTaxGroupCode": "",
        "ServiceOrderNumber": "",
        "IsDeliveryAddressOrderSpecific": "No",
        "CustomerRequisitionNumber": "",
        "SalesOrderNumber": "6FMB",
        "FiscalDocumentTypeId": "",
        "PlanningPriority": 0,
        "DeliveryCFOPCode": "",
        "LineDiscountPercentage": 0,
        "SalesPrice": 2887.5,
        "GiftCardGiftMessage": "",
        "SalesOrderLineCreationMethod": "SalesOrder",
        "FulfillmentStatus": "Unknown",
        "OrderedCatchWeightQuantity": 0,
        "RetailCalculatedPeriodicDiscountPercentage": 0,
        "OrderLineReference": "",
        "AllowedUnderdeliveryPercentage": 0,
        "DeliveryAddressCityInKana": "",
        "AllowedOverdeliveryPercentage": 0,
        "Catalog": 0,
        "DeliveryAddressLongitude": 0,
        "IntrastatCommodityCode": "",
        "LineNumber": 1,
        "DefaultLedgerDimensionDisplayValue": "15---",
        "DeliveryAddressTimeZone": null,
        "ProductColorId": "",
        "GiftCardRecipientName": "",
        "CFOPCode": "",
        "DeliverySalesTaxItemGroupCode": "",
        "DeliveryAddressStateId": "MA",
        "DeliveryBuildingCompliment": "",
        "IntrastatTransportModeCode": "",
        "DeliveryAddressPostBox": "",
        "CustomersLineNumber": 0,
        "CustomsDocumentDate": "1900-01-01T12:00:00Z",
        "GiftCardType": "Email",
        "LineAmount": 25987.5,
        "IntrastatPortId": "",
        "IntrastatSpecialMovementCode": "",
        "FinTagDisplayValue": "",
        "SalesPriceQuantity": 1,
        "WillRebateCalculationExcludeLine": "No",
        "RetailCalculatedTenderDiscountAmount": 0,
        "SuframaDiscountPercentage": 0,
        "InventoryReservationMethod": "None",
        "RequestedShippingDate": "2017-11-28T12:00:00Z",
        "RetailCalculatedManualLineDiscountAmount": 0,
        "WithholdingTaxGroupCode": "",
        "FulfillmentStoreId": "",
        "SkipCreateAutoCharges": "Yes",
        "ExternalItemNumber": "",
        "IntrastatStatisticValue": 0,
        "IsLineStopped": "No",
        "GiftCardBuyerEmail": ""
    },
    {
        "@odata.etag": "W/\"JzIwNjM2MTIxNzQsNTYzNzE1MjgzNDswLDA7NzMyMTc1MDQ1LDU2MzcyOTc2NDM7MCwwOzAsMDswLDA7MCwwJw==\"",
        "dataAreaId": "gfs",
        "InventoryLotId": "LOTI-041119",
        "RequestedReceiptDate": "2017-12-13T12:00:00Z",
        "DefaultLineNumberFromLineCreationSequenceNumber": "No",
        "RetailCalculatedTotalDiscountPercentage": 0,
        "EInvoiceDimensionAccountCode": "",
        "FormattedDelveryAddress": "501 ARBORWAY\nJAMAICA PLAIN, MA 02130 \nUSA",
        "ShippingWarehouseLocationId": "",
        "SalesOrderLineStatus": "Invoiced",
        "ProjectCategoryId": "",
        "ExcludeFromMasterPlanning": "No",
        "ItemNumber": "19716",
        "DeliveryAddressDescription": "BICON DENTAL IMPLANTS",
        "MultilineDiscountPercentage": 0,
        "ShippingWarehouseId": "15",
        "GiftCardBuyerName": "",
        "GiftCardNumber": "",
        "CustomsDocumentNumber": "",
        "LineDiscountAmount": 0,
        "ProductStyleId": "",
        "ProductConfigurationId": "",
        "DeliverySalesTaxGroupCode": "",
        "IsIntrastatTriangularDeal": "No",
        "MultilineDiscountAmount": 0,
        "ItemBatchNumber": "",
        "DeliveryAddressCountryRegionId": "USA",
        "DeliveryAddressLatitude": 0,
        "IsPriceLocked": "No",
        "DeliveryAddressCity": "JAMAICA PLAIN",
        "SalesProductCategoryName": "",
        "SalesOrderPromisingMethod": "None",
        "ProjectId": "",
        "DeliveryAddressDistrictName": "",
        "ProjectLinePropertyId": "",
        "SalesRebateProductGroupId": "",
        "DeliveryAddressCountyId": "Suffolk",
        "SalesUnitSymbol": "ea",
        "SalesDeliverNow": 0,
        "ItemWithholdingTaxCodeGroupCode": "",
        "ConfirmedReceiptDate": "1900-01-01T12:00:00Z",
        "ProductSizeId": "",
        "FixedPriceCharges": 0,
        "DeliveryAddressZipCode": "02130",
        "DeliveryAddressDunsNumber": "",
        "DeliveryTermsId": "COL",
        "IsSoftReservedExternally": "No",
        "ServiceFiscalInformationCode": "",
        "RetailCalculatedTotalDiscountAmount": 0,
        "DeliveryAddressName": "BICON DENTAL IMPLANTS",
        "PackingUnitSymbol": "",
        "OrderedSalesQuantity": 5,
        "BOMId": "",
        "CreditNoteReasonCode": "",
        "DeliveryAddressStreetNumber": "",
        "DeliveryAddressStreetInKana": "",
        "ShippingSiteId": "15",
        "NGPCode": 0,
        "RetailCalculatedLineDiscountAmount": 0,
        "IsDeliveryAddressPrivate": "No",
        "LineCreationSequenceNumber": 1,
        "RetailCalculatedTenderDiscountPercentage": 0,
        "InventoryServiceReservationId": "",
        "MainAccountIdDisplayValue": "",
        "OrderedInventoryStatusId": "Available",
        "GiftCardRecipientEmail": "",
        "DeliveryAddressCountryRegionISOCode": "US",
        "ItemSerialNumber": "",
        "RetailCalculatedManualLineDiscountPercentage": 0,
        "CalculateLineAmount": "Yes",
        "RetailCalculatedPeriodicDiscountAmount": 0,
        "IntrastatTransactionCode": "",
        "CurrencyCode": "USD",
        "DeliveryAddressLocationId": "000087670",
        "RouteId": "",
        "SalesTaxItemGroupCode": "",
        "EInvoicePropertyNumber": "",
        "ProductVersionId": "",
        "CommissionSalesRepresentativeGroupId": "",
        "CustomsDocumentName": "",
        "WillAutomaticInventoryReservationConsiderBatchAttributes": "No",
        "IntrastatStatisticsProcedureCode": "",
        "OverrideSalesTax": "No",
        "LineDescription": "",
        "DeliveryAddressStreet": "501 ARBORWAY",
        "DeliveryModeCode": "UPS",
        "ConfirmedShippingDate": "1900-01-01T12:00:00Z",
        "FullRunCTPStatus": "Ready",
        "RetailCalculatedLineDiscountPercentage": 0,
        "SalesTaxGroupCode": "",
        "ServiceOrderNumber": "",
        "IsDeliveryAddressOrderSpecific": "No",
        "CustomerRequisitionNumber": "",
        "SalesOrderNumber": "6FMH",
        "FiscalDocumentTypeId": "",
        "PlanningPriority": 0,
        "DeliveryCFOPCode": "",
        "LineDiscountPercentage": 0,
        "SalesPrice": 1443.73,
        "GiftCardGiftMessage": "",
        "SalesOrderLineCreationMethod": "SalesOrder",
        "FulfillmentStatus": "Unknown",
        "OrderedCatchWeightQuantity": 0,
        "RetailCalculatedPeriodicDiscountPercentage": 0,
        "OrderLineReference": "",
        "AllowedUnderdeliveryPercentage": 0,
        "DeliveryAddressCityInKana": "",
        "AllowedOverdeliveryPercentage": 0,
        "Catalog": 0,
        "DeliveryAddressLongitude": 0,
        "IntrastatCommodityCode": "",
        "LineNumber": 1,
        "DefaultLedgerDimensionDisplayValue": "15---",
        "DeliveryAddressTimeZone": null,
        "ProductColorId": "",
        "GiftCardRecipientName": "",
        "CFOPCode": "",
        "DeliverySalesTaxItemGroupCode": "",
        "DeliveryAddressStateId": "MA",
        "DeliveryBuildingCompliment": "",
        "IntrastatTransportModeCode": "",
        "DeliveryAddressPostBox": "",
        "CustomersLineNumber": 0,
        "CustomsDocumentDate": "1900-01-01T12:00:00Z",
        "GiftCardType": "Email",
        "LineAmount": 7218.65,
        "IntrastatPortId": "",
        "IntrastatSpecialMovementCode": "",
        "FinTagDisplayValue": "",
        "SalesPriceQuantity": 1,
        "WillRebateCalculationExcludeLine": "No",
        "RetailCalculatedTenderDiscountAmount": 0,
        "SuframaDiscountPercentage": 0,
        "InventoryReservationMethod": "None",
        "RequestedShippingDate": "2017-12-13T12:00:00Z",
        "RetailCalculatedManualLineDiscountAmount": 0,
        "WithholdingTaxGroupCode": "",
        "FulfillmentStoreId": "",
        "SkipCreateAutoCharges": "Yes",
        "ExternalItemNumber": "",
        "IntrastatStatisticValue": 0,
        "IsLineStopped": "No",
        "GiftCardBuyerEmail": ""
    },
    {
        "@odata.etag": "W/\"JzU1Mjk4NDYxMyw1NjM3MTUyODQ0OzAsMDswLDA7MCwwOzAsMDswLDA7MCwwJw==\"",
        "dataAreaId": "gfs",
        "InventoryLotId": "LOTI-041129",
        "RequestedReceiptDate": "1900-01-01T12:00:00Z",
        "DefaultLineNumberFromLineCreationSequenceNumber": "No",
        "RetailCalculatedTotalDiscountPercentage": 0,
        "EInvoiceDimensionAccountCode": "",
        "FormattedDelveryAddress": "",
        "ShippingWarehouseLocationId": "",
        "SalesOrderLineStatus": "Invoiced",
        "ProjectCategoryId": "",
        "ExcludeFromMasterPlanning": "No",
        "ItemNumber": "47433",
        "DeliveryAddressDescription": "",
        "MultilineDiscountPercentage": 0,
        "ShippingWarehouseId": "10",
        "GiftCardBuyerName": "",
        "GiftCardNumber": "",
        "CustomsDocumentNumber": "",
        "LineDiscountAmount": 0,
        "ProductStyleId": "",
        "ProductConfigurationId": "",
        "DeliverySalesTaxGroupCode": "",
        "IsIntrastatTriangularDeal": "No",
        "MultilineDiscountAmount": 0,
        "ItemBatchNumber": "",
        "DeliveryAddressCountryRegionId": "",
        "DeliveryAddressLatitude": 0,
        "IsPriceLocked": "No",
        "DeliveryAddressCity": "",
        "SalesProductCategoryName": "",
        "SalesOrderPromisingMethod": "None",
        "ProjectId": "",
        "DeliveryAddressDistrictName": "",
        "ProjectLinePropertyId": "",
        "SalesRebateProductGroupId": "",
        "DeliveryAddressCountyId": "",
        "SalesUnitSymbol": "ea",
        "SalesDeliverNow": 0,
        "ItemWithholdingTaxCodeGroupCode": "",
        "ConfirmedReceiptDate": "2018-02-05T12:00:00Z",
        "ProductSizeId": "",
        "FixedPriceCharges": 0,
        "DeliveryAddressZipCode": "",
        "DeliveryAddressDunsNumber": "",
        "DeliveryTermsId": "PPD&ADD",
        "IsSoftReservedExternally": "No",
        "ServiceFiscalInformationCode": "",
        "RetailCalculatedTotalDiscountAmount": 0,
        "DeliveryAddressName": "LUMIGEN/BECKMAN COULTER",
        "PackingUnitSymbol": "",
        "OrderedSalesQuantity": 10,
        "BOMId": "",
        "CreditNoteReasonCode": "",
        "DeliveryAddressStreetNumber": "",
        "DeliveryAddressStreetInKana": "",
        "ShippingSiteId": "10",
        "NGPCode": 0,
        "RetailCalculatedLineDiscountAmount": 0,
        "IsDeliveryAddressPrivate": "No",
        "LineCreationSequenceNumber": 1,
        "RetailCalculatedTenderDiscountPercentage": 0,
        "InventoryServiceReservationId": "",
        "MainAccountIdDisplayValue": "",
        "OrderedInventoryStatusId": "Available",
        "GiftCardRecipientEmail": "",
        "DeliveryAddressCountryRegionISOCode": "",
        "ItemSerialNumber": "",
        "RetailCalculatedManualLineDiscountPercentage": 0,
        "CalculateLineAmount": "Yes",
        "RetailCalculatedPeriodicDiscountAmount": 0,
        "IntrastatTransactionCode": "",
        "CurrencyCode": "USD",
        "DeliveryAddressLocationId": "",
        "RouteId": "",
        "SalesTaxItemGroupCode": "",
        "EInvoicePropertyNumber": "",
        "ProductVersionId": "",
        "CommissionSalesRepresentativeGroupId": "",
        "CustomsDocumentName": "",
        "WillAutomaticInventoryReservationConsiderBatchAttributes": "No",
        "IntrastatStatisticsProcedureCode": "",
        "OverrideSalesTax": "No",
        "LineDescription": "",
        "DeliveryAddressStreet": "",
        "DeliveryModeCode": "BEST WAY",
        "ConfirmedShippingDate": "2018-02-05T12:00:00Z",
        "FullRunCTPStatus": "Ready",
        "RetailCalculatedLineDiscountPercentage": 0,
        "SalesTaxGroupCode": "",
        "ServiceOrderNumber": "",
        "IsDeliveryAddressOrderSpecific": "No",
        "CustomerRequisitionNumber": "",
        "SalesOrderNumber": "6JZ7",
        "FiscalDocumentTypeId": "",
        "PlanningPriority": 0,
        "DeliveryCFOPCode": "",
        "LineDiscountPercentage": 0,
        "SalesPrice": 504,
        "GiftCardGiftMessage": "",
        "SalesOrderLineCreationMethod": "SalesOrder",
        "FulfillmentStatus": "Unknown",
        "OrderedCatchWeightQuantity": 0,
        "RetailCalculatedPeriodicDiscountPercentage": 0,
        "OrderLineReference": "",
        "AllowedUnderdeliveryPercentage": 0,
        "DeliveryAddressCityInKana": "",
        "AllowedOverdeliveryPercentage": 0,
        "Catalog": 0,
        "DeliveryAddressLongitude": 0,
        "IntrastatCommodityCode": "",
        "LineNumber": 1,
        "DefaultLedgerDimensionDisplayValue": "20---",
        "DeliveryAddressTimeZone": null,
        "ProductColorId": "",
        "GiftCardRecipientName": "",
        "CFOPCode": "",
        "DeliverySalesTaxItemGroupCode": "",
        "DeliveryAddressStateId": "",
        "DeliveryBuildingCompliment": "",
        "IntrastatTransportModeCode": "",
        "DeliveryAddressPostBox": "",
        "CustomersLineNumber": 0,
        "CustomsDocumentDate": "1900-01-01T12:00:00Z",
        "GiftCardType": "Email",
        "LineAmount": 5040,
        "IntrastatPortId": "",
        "IntrastatSpecialMovementCode": "",
        "FinTagDisplayValue": "",
        "SalesPriceQuantity": 1,
        "WillRebateCalculationExcludeLine": "No",
        "RetailCalculatedTenderDiscountAmount": 0,
        "SuframaDiscountPercentage": 0,
        "InventoryReservationMethod": "None",
        "RequestedShippingDate": "2017-12-31T12:00:00Z",
        "RetailCalculatedManualLineDiscountAmount": 0,
        "WithholdingTaxGroupCode": "",
        "FulfillmentStoreId": "",
        "SkipCreateAutoCharges": "Yes",
        "ExternalItemNumber": "",
        "IntrastatStatisticValue": 0,
        "IsLineStopped": "No",
        "GiftCardBuyerEmail": ""
    }
];

function jsonToCsv(jsonArray) {
    const headers = Object.keys(jsonArray[0]);
    const csvRows = [];


    csvRows.push(headers.join(','));


    for (const row of jsonArray) {
        const values = headers.map(header => {
            const val = row[header];
            const escaped = ('' + val).replace(/"/g, '""');
            return `"${escaped}"`;
        });
        csvRows.push(values.join(','));
    }

    return csvRows.join('\n');
}

function downloadCSV() {
    const csv = jsonToCsv(jsonData);
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.setAttribute('hidden', '');
    a.setAttribute('href', url);
    a.setAttribute('download', 'data.csv');
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
}